name: Ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build --verbose

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin -f

    - name: Run cargo-tarpaulin
      run: cargo tarpaulin --out Xml --verbose --all-features --run-types Tests --timeout 1200

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
